name: base
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - absl-py=0.13.0=py37haa95532_0
  - aiohttp=3.6.3=py37he774522_0
  - argon2-cffi=20.1.0=py37h2bbff1b_1
  - astor=0.8.1=py37haa95532_0
  - async-timeout=3.0.1=py37haa95532_0
  - async_generator=1.10=py37h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - blinker=1.4=py37haa95532_0
  - ca-certificates=2021.7.5=haa95532_1
  - cached-property=1.5.2=py_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.5.30=py37haa95532_0
  - cffi=1.14.0=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - click=8.0.1=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.10.3=py37haa95532_0
  - conda-package-handling=1.6.1=py37h62dcd97_0
  - console_shortcut=0.1.1=4
  - coverage=5.5=py37h2bbff1b_2
  - cryptography=2.9.2=py37h7a1dbc1_0
  - cython=0.29.24=py37hd77b12b_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - google-auth=1.28.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.36.1=py37hc60d5dd_1
  - hdf5=1.10.6=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.9=py_1
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.22.0=py37hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.17.0=py37_0
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.17.2=h23ce68f_1
  - libsodium=1.0.18=h62dcd97_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.4=py37haa95532_0
  - markupsafe=2.0.1=py37h2bbff1b_0
  - menuinst=1.4.16=py37he774522_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.0=py37h277e83a_2
  - mkl_random=1.2.2=py37hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - multidict=4.7.6=py37he774522_1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py37haa95532_0
  - numpy=1.20.3=py37ha4e8547_0
  - numpy-base=1.20.3=py37hc2deb75_0
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1k=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=20.9=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py37haa95532_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=20.0.2=py37_3
  - powershell_shortcut=0.0.1=3
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - protobuf=3.17.2=py37hd77b12b_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycosat=0.6.3=py37he774522_0
  - pycparser=2.20=py_0
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyjwt=2.0.1=py37haa95532_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - pyrsistent=0.17.3=py37he774522_0
  - pysocks=1.7.1=py37_0
  - python=3.7.7=h81c818b_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyzmq=20.0.0=py37hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.1.0=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - requests=2.23.0=py37_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel_yaml=0.15.87=py37he774522_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=46.4.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.31.1=h2a8f88b_1
  - tensorboard-plugin-wit=1.6.0=py_0
  - termcolor=1.1.0=py37haa95532_1
  - terminado=0.9.4=py37haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tornado=6.1=py37h2bbff1b_0
  - tqdm=4.46.0=py_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.25.8=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py37he774522_1
  - yaml=0.1.7=hc54c509_2
  - yarl=1.6.3=py37h2bbff1b_0
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - astunparse==1.6.3
    - ci-info==0.2.0
    - configobj==5.0.6
    - configparser==5.0.2
    - cycler==0.10.0
    - decorator==4.4.2
    - dill==0.3.4
    - etelemetry==0.2.2
    - filelock==3.0.12
    - fitz==0.0.1.dev2
    - future==0.18.2
    - gast==0.3.3
    - h5py==2.10.0
    - httplib2==0.19.1
    - importlib-metadata==4.5.0
    - isodate==0.6.0
    - joblib==1.0.1
    - keras==2.4.3
    - kiwisolver==1.3.1
    - lxml==4.6.3
    - matplotlib==3.4.2
    - networkx==2.5.1
    - nibabel==3.2.1
    - nipype==1.6.0
    - pandas==1.2.4
    - pathlib==1.0.1
    - pillow==8.3.1
    - prov==2.0.0
    - pybind11==2.7.1
    - pydot==1.4.2
    - pytz==2021.1
    - pyxnat==1.4
    - pyyaml==5.4.1
    - rdflib==5.0.0
    - scikit-learn==0.24.2
    - scipy==1.4.1
    - seaborn==0.11.1
    - simplejson==3.17.2
    - sklearn==0.0
    - sourceinspect==0.0.4
    - taichi==0.8.0
    - tensorboard==2.2.2
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - threadpoolctl==2.2.0
    - traits==6.2.0
    - typing-extensions==3.10.0.0
prefix: C:\Users\dirac\miniconda3
